# -*- coding: utf-8 -*-
"""AluraStore.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/12Oc_Cy2_7kTk6iOKDb99vb3xX3VNUNm5

### Importação dos dados
"""

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns


url = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_1.csv"
url2 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_2.csv"
url3 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_3.csv"
url4 = "https://raw.githubusercontent.com/alura-es-cursos/challenge1-data-science/refs/heads/main/base-de-dados-challenge-1/loja_4.csv"

loja = pd.read_csv(url)
loja2 = pd.read_csv(url2)
loja3 = pd.read_csv(url3)
loja4 = pd.read_csv(url4)

loja.head()

"""#1. Análise do faturamento

"""

#Primeiro vamos criar uma lista das lojas, para poder usar laço e evitar muitas linhas
lista_lojas = [loja, loja2, loja3, loja4]  # Cada item é um df
nomes_lojas = ['Loja 1', 'Loja 2', 'Loja 3', 'Loja 4']
lista_faturamento = []

# Loop sobre os DataFrames
for loja in lista_lojas:
    faturamento_loja = float(loja['Preço'].sum())
    lista_faturamento.append(faturamento_loja)

# Monta dicionário para organizar por chave e valor
dicionario_faturamento = dict(zip(nomes_lojas, lista_faturamento))

# Exibe os faturamentos brutos do maior para o menor
for loja, faturamento in sorted(dicionario_faturamento.items(), key=lambda x: x[1], reverse=True):
    print(f'\n📊 O faturamento bruto da {loja.lower()} foi de R${faturamento:.2f}')



"""# 2. Vendas por Categoria

"""

# Primeiro tentei agrupar todos os dados em uma lista mas ficou poluido, decidi explorar o df
df_vendas_categoria = pd.DataFrame()

# Loop sobre as lojas e agrupar as vendas por categoria
for i, loja in enumerate(lista_lojas):
    qtd_produtos_categoria = loja['Categoria do Produto'].value_counts()  # Conta as vendas por categoria
    df_vendas_categoria[nomes_lojas[i]] = qtd_produtos_categoria  # Adiciona no DataFrame (similar ao .append)

# Ordenar as categorias de cada loja pela quantidade de vendas (do maior para o menor)
df_vendas_categoria = df_vendas_categoria.sort_values(by=nomes_lojas[0], ascending=False)

# Exibe o DataFrame de vendas por categoria
print("📊 Vendas por Categoria em cada Loja:")
print(df_vendas_categoria)

# Exibe as 5 categorias mais populares por loja
for loja, qtd in df_vendas_categoria.items():
    print(f'\n📌 {loja} - Top 5 categorias:')
    top_5 = qtd.head(5)  # Filtra as 5 mais populares
    for categoria, total in top_5.items():
        print(f'  🛒 {categoria.title()}: {total} vendas')

# Configura o tamanho total da figura (gráfico maior com 4 subgráficos)
plt.figure(figsize=(10, 8))

# Loop para criar cada gráfico
for i, loja in enumerate(df_vendas_categoria.columns):
    # Cria um subgráfico para cada loja
    plt.subplot(2, 2, i+1)  # A numeração começa do 1

    # Obter os valores e categorias
    categorias = df_vendas_categoria.index
    vendas = df_vendas_categoria[loja]

    # Identificar o índice do máximo e mínimo
    max_idx = vendas.idxmax()
    min_idx = vendas.idxmin()

    # Cor padrão para as barras
    cor_padrao = 'gray'

    # Plotar todas as barras
    bars = plt.barh(categorias, vendas, color=cor_padrao)

    # Colorir a barra do máximo e mínimo
    bars[categorias.get_loc(max_idx)].set_color('green')  # Máximo em verde
    bars[categorias.get_loc(min_idx)].set_color('red')   # Mínimo em vermelho

    # Títulos e rótulos do gráfico
    plt.xlabel('Quantidade de Vendas')
    plt.ylabel('Categoria')
    plt.title(f'Vendas por Categoria - {loja}')
    plt.grid(axis='x')

# Ajusta o layout para que não sobreponha os gráficos
plt.tight_layout()

# Exibe o gráfico
plt.show()

"""# 3. Média de Avaliação das Lojas"""

# Cria um dicionário para armazenar as médias
medias_avaliacao = {}
medias_avaliacao_produtos = {}

# Loop para calcular a média de cada loja
for i, loja in enumerate(lista_lojas):
    nome_loja = nomes_lojas[i]
    media = round(loja['Avaliação da compra'].mean(), 2)
    medias_avaliacao[nome_loja] = media

# Loop para calcular a média por categoria de produto por loja
for i, loja in enumerate(lista_lojas):
    nome_loja = nomes_lojas[i]
    media_produtos = loja.groupby('Categoria do Produto')['Avaliação da compra'].mean().round(2)
    medias_avaliacao_produtos[nome_loja] = media_produtos

# DataFrame com média geral das lojas
df_media_avaliacao = pd.DataFrame.from_dict(medias_avaliacao, orient='index', columns=['Média de Avaliação'])
df_media_avaliacao = df_media_avaliacao.sort_values(by='Média de Avaliação', ascending=False)

# DataFrame com média por categoria (transposto para lojas como linhas)
df_media_avaliacao_produtos = pd.DataFrame(medias_avaliacao_produtos).T

# Exibe o resultado
print("📊 Média de Avaliação das Lojas:")
print(df_media_avaliacao)

# Exibe as 3 categorias melhor avaliadas por loja
for loja, avaliacoes in df_media_avaliacao_produtos.iterrows():
    print(f'\n {loja} - Top 5 categorias melhor avaliadas:')
    top_3 = avaliacoes.sort_values(ascending=False).head(3)
    for categoria, media in top_3.items():
        print(f'   {categoria.title()}: {media}')

plt.figure(figsize=(12, 8))
sns.heatmap(df_media_avaliacao_produtos, annot=True, cmap='YlGnBu', linewidths=.5, fmt=".2f")
plt.title('Média de Avaliação por Categoria em Cada Loja')
plt.xlabel('Categoria do Produto')
plt.ylabel('Loja')
plt.show()

"""# 4. Produtos Mais e Menos Vendidos"""

df_vendas_produtos = pd.DataFrame()

# Loop para contar os produtos vendidos em cada loja
for i, loja in enumerate(lista_lojas):
    qtd_vendas_produtos = loja['Produto'].value_counts()
    df_vendas_produtos[nomes_lojas[i]] = qtd_vendas_produtos

# Mostra os Top 5 e Bottom 5 produtos para cada loja
for loja, qtd in df_vendas_produtos.items():
    print(f'\n📌 {loja} - Top 5 produtos:')
    top_3 = qtd.sort_values(ascending=False).head(3)
    for produto, total in top_3.items():
        print(f'  🛒 {produto.title()}: {total} vendas')

    print(f'\n📌 {loja} - Bottom 5 produtos:')
    bottom_3 = qtd.sort_values(ascending=True).head(3)
    for produto, total in bottom_3.items():
        print(f'  📉 {produto.title()}: {total} vendas')

# Define o número de lojas
num_lojas = len(nomes_lojas)

# Cria subplots (um por loja)
fig, axs = plt.subplots(1, num_lojas, figsize=(5*num_lojas, 5), constrained_layout=True)

for i, loja in enumerate(nomes_lojas):
    dados = df_vendas_produtos[loja]
    top_3 = dados.sort_values(ascending=False).head(3)
    bottom_3 = dados.sort_values().head(3)

    # Junta os melhores e piores com concat em vez de append(descontinuado no pandas)
    produtos = pd.concat([top_3, bottom_3])
    cores = ['green']*3 + ['red']*3

    axs[i].barh(produtos.index, produtos.values, color=cores)
    axs[i].set_title(f'{loja} - Top & Bottom 3')
    axs[i].invert_yaxis()  # Top fica em cima
    axs[i].set_xlabel('Qtd de Vendas')

plt.show()

"""# 5. Frete Médio por Loja

"""

lista_frete = []

# Loop sobre os DataFrames
for loja in lista_lojas:
    frete_loja = float(loja['Frete'].mean())
    lista_frete.append(frete_loja)

lista_frete_total = []

for loja in lista_lojas:
    soma_frete = float(loja['Frete'].sum())
    lista_frete_total.append(soma_frete)

# Monta dicionário para organizar por chave e valor
dicionario_frete = dict(zip(nomes_lojas, lista_frete))

# Monta dicionário para organizar por chave e valor
dicionario_frete_total = dict(zip(nomes_lojas, lista_frete_total))

# Exibe a média de frete do maior para o menor
for loja, frete in sorted(dicionario_frete.items(), key=lambda x: x[1], reverse=True):
    print(f'📊 A média da {loja.lower()} foi de R${frete:.2f}')

# Exibe a soma de frete do maior para o menor
for loja, frete_total in sorted(dicionario_frete_total.items(), key=lambda x: x[1], reverse=True):
    print(f'\n📊 A soma dos fretes da {loja.lower()} foi de R${frete_total:.2f}')

import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

# Cria uma lista de dataframes e nomes
lista_lojas = [loja, loja2, loja3, loja4]
nomes_lojas = ['Loja 1', 'Loja 2', 'Loja 3', 'Loja 4']

# Lista para guardar os dataframes de contagem por loja
dados_heatmap = []

for i, df_loja in enumerate(lista_lojas):
    # Conta quantos produtos foram vendidos por categoria
    contagem = df_loja['Categoria do Produto'].value_counts().reset_index()
    contagem.columns = ['Categoria do Produto', 'Quantidade de Vendas']
    contagem['Loja'] = nomes_lojas[i]
    dados_heatmap.append(contagem)

# Concatena todas as lojas
df_total = pd.concat(dados_heatmap)

# Converte para tabela pivot para o heatmap
df_pivot = df_total.pivot(index='Loja', columns='Categoria do Produto', values='Quantidade de Vendas').fillna(0)

# Cria o heatmap
plt.figure(figsize=(12, 8))
sns.heatmap(df_pivot, annot=True, cmap='YlGnBu', linewidths=.5, fmt=".0f")
plt.title('Quantidade de Vendas por Categoria em Cada Loja')
plt.xlabel('Categoria do Produto')
plt.ylabel('Loja')
plt.show()

# Cria um dicionário para guardar os DataFrames
lista_lojas = [loja, loja2, loja3, loja4]
nomes_lojas = ['Loja 1', 'Loja 2', 'Loja 3', 'Loja 4']

# Lista para armazenar os DataFrames de cada loja com média de latitude por categoria
dados_lat = []

for nome, df in zip(nomes_lojas, lista_lojas):
    medias = df.groupby('Categoria do Produto')['lat'].mean()
    dados_lat.append(medias.rename(nome))

# Concatena os resultados e transpõe
df_media_lat = pd.concat(dados_lat, axis=1).T

# Heatmap das médias de latitude
plt.figure(figsize=(14, 8))
sns.heatmap(df_media_lat, annot=True, cmap='YlOrBr', linewidths=0.5, fmt=".2f")
plt.title('Média da Latitude por Categoria em Cada Loja')
plt.xlabel('Categoria do Produto')
plt.ylabel('Loja')
plt.show()

"""# Relatório Final

## Faturamento Bruto por loja:

📊 O faturamento bruto da loja 1 foi de R$1.534.509,12

📊 O faturamento bruto da loja 2 foi de R$1.488.459,06

📊 O faturamento bruto da loja 3 foi de R$1.464.025,03

📊 O faturamento bruto da loja 4 foi de R$1.384.497,58

---

## Vendas por Categoria em cada Loja:

| Categoria do Produto     | Loja 1 | Loja 2 | Loja 3 | Loja 4 |
|--------------------------|--------|--------|--------|--------|
| Móveis                   | 465    | 442    | 499    | 480    |
| Eletrônicos              | 448    | 422    | 451    | 451    |
| Brinquedos               | 324    | 313    | 315    | 338    |
| Eletrodomésticos         | 312    | 305    | 278    | 254    |
| Esporte e Lazer          | 284    | 275    | 277    | 277    |
| Instrumentos Musicais    | 182    | 224    | 177    | 170    |
| Livros                   | 173    | 197    | 185    | 187    |
| Utilidades Domésticas    | 171    | 181    | 177    | 201    |

---

## 📌 Loja 1 - Top 5 categorias:

🛒 Móveis: 465 vendas

🛒 Eletrônicos: 448 vendas

🛒 Brinquedos: 324 vendas

🛒 Eletrodomésticos: 312 vendas

🛒 Esporte e Lazer: 284 vendas

---

## 📌 Loja 2 - Top 5 categorias:

🛒 Móveis: 442 vendas

🛒 Eletrônicos: 422 vendas

🛒 Brinquedos: 313 vendas

🛒 Eletrodomésticos: 305 vendas

🛒 Esporte e Lazer: 275 vendas

---

## 📌 Loja 3 - Top 5 categorias:

🛒 Móveis: 499 vendas

🛒 Eletrônicos: 451 vendas

🛒 Brinquedos: 315 vendas

🛒 Eletrodomésticos: 278 vendas

🛒 Esporte e Lazer: 277 vendas

---

## 📌 Loja 4 - Top 5 categorias:

🛒 Móveis: 480 vendas

🛒 Eletrônicos: 451 vendas

🛒 Brinquedos: 338 vendas

🛒 Eletrodomésticos: 254 vendas

🛒 Esporte e Lazer: 277 vendas

---

## Média de Avaliação das Lojas:

| Loja   | Média de Avaliação |
|--------|---------------------|
| Loja 3 | 4.05                |
| Loja 2 | 4.04                |
| Loja 4 | 4.00                |
| Loja 1 | 3.98                |

---

| Loja   | Categoria               | Avaliação |
|--------|-------------------------|-----------|
| Loja 1 | Brinquedos              | 4.08      |
| Loja 1 | Instrumentos Musicais   | 4.05      |
| Loja 1 | Eletrodomésticos        | 4.03      |
| Loja 2 | Móveis                  | 4.09      |
| Loja 2 | Eletrodomésticos        | 4.07      |
| Loja 2 | Utilidades Domésticas   | 4.07      |
| Loja 3 | Brinquedos              | 4.20      |
| Loja 3 | Móveis                  | 4.10      |
| Loja 3 | Utilidades Domésticas   | 4.07      |
| Loja 4 | Esporte e Lazer         | 4.05      |
| Loja 4 | Livros                  | 4.04      |
| Loja 4 | Utilidades Domésticas   | 4.01      |

---

## 📌 Loja 1

### 🛒 Top 5 produtos

| Produto             | Vendas |
|---------------------|--------|
| Micro-Ondas         | 60     |
| Tv Led UHD 4K       | 60     |
| Guarda Roupas       | 60     |

### 📉 Bottom 5 produtos

| Produto             | Vendas |
|---------------------|--------|
| Headset             | 33     |
| Celular ABXY        | 33     |
| Panela de Pressão   | 35     |

---

## 📌 Loja 2

### 🛒 Top 5 produtos

| Produto                  | Vendas |
|--------------------------|--------|
| Iniciando em Programação | 65     |
| Micro-Ondas              | 62     |
| Bateria                  | 61     |

### 📉 Bottom 5 produtos

| Produto             | Vendas |
|---------------------|--------|
| Jogo de Tabuleiro   | 32     |
| Impressora          | 34     |
| Mesa de Jantar      | 34     |

---

## 📌 Loja 3

### 🛒 Top 5 produtos

| Produto        | Vendas |
|----------------|--------|
| Kit Banquetas  | 57     |
| Cama King      | 56     |
| Mesa de Jantar | 56     |

### 📉 Bottom 5 produtos

| Produto            | Vendas |
|--------------------|--------|
| Blocos de Montar   | 35     |
| Micro-Ondas        | 36     |
| Mochila            | 36     |

---

## 📌 Loja 4

### 🛒 Top 5 produtos

| Produto     | Vendas |
|-------------|--------|
| Cama Box    | 62     |
| Faqueiro    | 59     |
| Cama King   | 56     |

### 📉 Bottom 5 produtos

| Produto         | Vendas |
|------------------|--------|
| Guitarra         | 33     |
| Guarda Roupas    | 34     |
| Violão           | 37     |

---

## 🚚 Frete por Loja

- A média do frete na Loja 1 foi de R$34.69, totalizando R$81.837,97 em fretes.
- Na Loja 2, a média foi de R$33.62, com uma soma total de R$79.314,16.
- Já a Loja 3 teve uma média de R$33.07, somando R$78.022,66.
- Por fim, a Loja 4 apresentou a menor média, com R$31.28, e um total de R$73.755,88 em fretes.







"""

